name: Github Actions Commit

on:
  workflow_dispatch:
  schedule:  # 每 2 小时执行一次
    - cron: '0 */2 * * *'  
  repository_dispatch:  # 通过 API 触发
    types: start_action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 使用最新版本

    - name: Configure Git
      run: |
        git config --global user.name "Biang8"
        git config --global user.email "${{ secrets.EMAIL }}"  # 确保 EMAIL 已在 GitHub Secrets 设置

    - name: Initialize the repository if it's empty
      run: |
        if ! git rev-parse --verify HEAD; then
          git checkout -b main
          git commit --allow-empty -m "Initial commit"
          git push origin main
        fi

    - name: Create an empty commit
      run: |
        git commit --allow-empty -m "My amazing commit"

    - name: Determine the branch name
      id: branch_name
      run: echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV

    - name: Push changes
      run: |
        git push origin ${{ env.branch }}